version: '3.11'
services:
  dragonsden:
    build: .
    restart: on-failure
    command:
      sh -c "
      python3 manage.py migrate &&
      gunicorn dragonsden.wsgi:application
      --bind 0.0.0.0:6776
      --workers 2
      --timeout 120
      "
    volumes:
      - .:/usr/src/app/
    ports:
      - 6776:6776

